server:
  port: 8761
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
    register-with-eureka: false  #只当server
    fetch-registry: false
security:
  basic:
    enabled: true
  user:
    name: user
    password: password
